name: Sync Project Docs

on:
  # Per avviarlo a mano dal tab "Actions"
  workflow_dispatch:
  
  # Ogni volta che fai push su questo sito (BugBusterSite)
  push:
    branches:
      - main

jobs:
  build-and-sync:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write # Permesso di fare commit sul BugBusterSite

    steps:
      # 1. Scarica il codice di questo sito (BugBusterSite)
      - name: Checkout website repo
        uses: actions/checkout@v4

      # 2. Installa Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      # 3. Installa la libreria 'requests' (serve allo script Python)
      - name: Install dependencies
        run: pip install requests

      # 4. Esegue lo script Python
      - name: Run Sync Script (Fetch public docs)
        run: python .github/scripts/sync_verbali.py

      # 5. Salva (commit) le modifiche solo se index.html è cambiato
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'CI: Aggiorna lista documenti'
          file_pattern: 'index.html'