name: Sync Project Docs

on:
  # Per avviarlo a mano dal tab "Actions"
  workflow_dispatch:
  
  # Ogni volta che fai push su questo sito (BugBusterSite)
  push:
    branches:
      - main

  # Permette a un'altra repository (es. DocumentazioneSWE) di scatenare la sincronizzazione
  # usando repository_dispatch con event_type: 'documentazione_swe_push'
  repository_dispatch:
    types: [documentazione_swe_push]

jobs:
  build-and-sync:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write # Permesso di fare commit sul BugBusterSite

    steps:
      # 1. Scarica il codice di questo sito (BugBusterSite)
      - name: Checkout website repo
        uses: actions/checkout@v4

      # 2. Installa Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      # 3. Installa la libreria 'requests' (serve allo script Python)
      - name: Install dependencies
        run: pip install requests

      # 4. Esegue lo script Python
      - name: Run Sync Script (Fetch public docs)
        run: python .github/scripts/sync_verbali.py

      # 5. Salva (commit) le modifiche solo se index.html è cambiato
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'CI: Aggiorna lista documenti e PDF scaricati'
          file_pattern: '.'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: '41898282+github-actions[bot]@users.noreply.github.com'